#!/bin/bash -xe

if [ `id -u` -ne 0 ]; then
   echo "ABORT: Current user is not privileged"
   exit 4
fi

username="$1"

echo "Adding user $username ..." > /dev/null
adduser "$@" || exit 2  # $@ will resolve to all positional parameters. The equivalent of "*args" in Python.
if passwd --status $username | grep --quiet 'locked'; then 
   passwd $username || exit 3
fi

sudo -u $username configurebashrc
#sudo -u $username sh -c 'mkdir -p ~/Documents'
sudo -u $username sh -c 'ln -s /data/shared ~/shared_documents'
